export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const RESET_LOGIN = 'RESET_LOGIN';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const RESET_SIGN_UP = 'RESET_SIGN_UP';

export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAILURE = 'ACTIVATE_ACCOUNT_FAILURE';
export const RESET = 'RESET';

export const FETCH_REF_DATA_SUCCESS = 'FETCH_REF_DATA_SUCCESS';
export const FETCH_REF_DATA_FAILURE = 'FETCH_REF_DATA_FAILURE';

export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAILURE = 'CREATE_PROPERTY_FAILURE';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';